version: "3.9"

services:
  minio:
    image: minio/minio
    container_name: cdn-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/var/lib/minio
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    command: server --console-address ":9001" /var/lib/minio
    networks:
      - gominio-cdn-api

  golang:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cdn-golang
    restart: always
    networks:
      - gominio-cdn-api

networks:
  gominio-cdn-api:

volumes:
  minio: